In [259]:
from inclearn.lib.data import IncrementalDataset
import numpy as np
from inclearn.lib import factory, network, utils
import torch

In [260]:
d=IncrementalDataset('cifar100')

Files already downloaded and verified
Files already downloaded and verified


In [261]:
x,y = d.data_train, d.targets_train

In [262]:
x.shape

(50000, 32, 32, 3)

In [263]:
y.shape

(50000,)

In [264]:
idxes = np.where(y == 99)[0]

In [265]:
idxes2 = np.where(y == 1)[0]

In [266]:
idx_order=d.get_idx_order(y,1)

In [270]:
np.random.shuffle(idxes)

In [273]:
d.data_train[idxes].shape

(500, 32, 32, 3)

In [23]:
d._increment_num

10

In [24]:
len(y)

50000

In [25]:
s = 0
for i, item in idx_order.items():
    s += len(item)
print(s)

50000


In [26]:
task0_classes = y[idx_order[0]]
unique, counts = np.unique(task0_classes, return_counts=True)
print(dict(zip(unique, counts)))

{0: 500, 1: 500, 2: 500, 3: 500, 4: 500, 5: 500, 6: 500, 7: 500, 8: 500, 9: 500, 10: 500, 11: 500, 12: 500, 13: 500, 14: 500, 15: 500, 16: 500, 17: 500, 18: 500, 19: 500, 20: 500, 21: 500, 22: 500, 23: 500, 24: 500, 25: 500, 26: 500, 27: 500, 28: 500, 29: 500, 30: 500, 31: 500, 32: 500, 33: 500, 34: 500, 35: 500, 36: 500, 37: 500, 38: 500, 39: 500, 40: 500, 41: 500, 42: 500, 43: 500, 44: 500, 45: 500, 46: 500, 47: 500, 48: 500, 49: 500, 50: 500, 51: 500, 52: 500, 53: 500, 54: 500, 55: 500, 56: 500, 57: 500, 58: 500, 59: 500, 60: 500, 61: 500, 62: 500, 63: 500, 64: 500, 65: 500, 66: 500, 67: 500, 68: 500, 69: 500, 70: 500, 71: 500, 72: 500, 73: 500, 74: 500, 75: 500, 76: 500, 77: 500, 78: 500, 79: 500, 80: 500, 81: 500, 82: 500, 83: 500, 84: 500, 85: 500, 86: 500, 87: 500, 88: 500, 89: 500, 90: 500, 91: 500, 92: 500, 93: 500, 94: 500, 95: 500, 96: 500, 97: 500, 98: 500, 99: 500}


In [21]:
assert not set(idx_order[0]).intersection(idx_order[1])

In [29]:
x[range(0, x.shape[0])].shape

(50000, 32, 32, 3)

In [32]:
{i: np.array(range(0, y.shape[0])) for i in range(0, d._increment_num)}

{0: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 1: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 2: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 3: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 4: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 5: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 6: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 7: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 8: array([    0,     1,     2, ..., 49997, 49998, 49999]),
 9: array([    0,     1,     2, ..., 49997, 49998, 49999])}

In [34]:
y

array([ 1,  1,  1, ..., 92, 92, 92])

In [218]:
i, loader = d.get_custom_loader([3,1], shuffle=True)
x, y = next(iter(loader))
targets = utils.to_onehot(y, 5)

In [219]:
targets

tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0

In [220]:
values, indices = targets.max(1)

In [221]:
indices

tensor([3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3,
        3, 3, 1, 1, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 1, 3, 1, 3, 1,
        1, 3, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3,
        3, 1, 3, 3, 1, 1, 3, 3, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
        3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3,
        3, 3, 1, 1, 1, 3, 3, 1])

In [255]:
def get_old_sample_weight_tensor(targets):
    train_loader = loader
    samples_trained_dict = {3: 1000, 1:2250}
    new_targets = targets.clone()
    old_targets = 0.5*targets.clone()
    
    # Get class counts in the train loader
    class_ids, counts = np.unique(train_loader.dataset.y, return_counts=True)
    new_sample_counts = dict(zip(class_ids, counts))
    
    # Get classes from targets
    _, class_tensor = targets.max(1)
    
    class_weights = {}
    for c in np.unique(class_tensor):
        class_weights[c] = get_old_sample_weight(samples_trained_dict.get(c, 0), new_sample_counts.get(c, 0))
    
    # Map
    weight_list = [class_weights[c.item()] for c in class_tensor]
    old_sample_weight_tensor = iterable_to_tensor(weight_list, 'cpu:0').unsqueeze(1)
    print(old_sample_weight_tensor)
    
    new_targets[..., :] = old_sample_weight_tensor * old_targets + (1 - old_sample_weight_tensor) * targets[..., :]
    
    return new_targets
    
def get_old_sample_weight(num_old_samples, num_new_samples):
    def func(x):
        return 1-(1/(1+(1/x)))

    if num_old_samples == 0:
        return 0
    elif num_new_samples == 0:
        raise ValueError("num_new_samples is 0, this does not make sense. Why are you calling this method?")
    else:
        ratio = num_new_samples/num_old_samples
        return func(ratio)

def iterable_to_tensor(l, device):
    return torch.from_numpy(np.array(list(l), dtype='double')).float().to(device)

In [256]:
new_targets=get_old_sample_weight_tensor(targets)

{1: 0.8181818181818181, 3: 0.7826086956521738}
tensor([[0.7826],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.7826],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.7826],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.7826],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.7826],
        [0.8182],
        [0.8182],
        [0.7826],
        [0.7826],
        [0.8182],
        [0.7826],

In [257]:
targets

tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0

In [258]:
new_targets

tensor([[0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6087, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5909, 0.0000, 0.0000, 0.0000],


In [196]:
indices2 = indices.clone()

In [123]:
n = indices2.numpy() 

In [124]:
n[0] = 14.2

In [125]:
indices2

tensor([14.2000, 10.0000, 15.0000, 10.0000, 15.0000, 10.0000, 15.0000, 10.0000,
        10.0000, 15.0000, 10.0000,  5.0000, 10.0000, 10.0000, 10.0000, 15.0000,
         5.0000, 10.0000,  5.0000,  5.0000, 10.0000, 10.0000,  5.0000, 10.0000,
         5.0000,  5.0000, 10.0000, 15.0000,  5.0000, 15.0000, 15.0000, 15.0000,
        10.0000, 10.0000,  5.0000, 15.0000,  5.0000,  5.0000,  5.0000, 10.0000,
        10.0000, 15.0000,  5.0000, 15.0000, 10.0000, 15.0000,  5.0000, 10.0000,
         5.0000, 15.0000, 15.0000, 15.0000, 10.0000, 15.0000, 15.0000, 10.0000,
        15.0000,  5.0000,  5.0000, 10.0000,  5.0000, 10.0000, 10.0000, 15.0000,
         5.0000,  5.0000, 10.0000, 15.0000, 10.0000, 15.0000, 10.0000, 10.0000,
        10.0000,  5.0000, 10.0000,  5.0000, 15.0000,  5.0000,  5.0000,  5.0000,
         5.0000,  5.0000, 15.0000, 10.0000, 15.0000, 15.0000, 10.0000,  5.0000,
         5.0000,  5.0000,  5.0000, 15.0000,  5.0000,  5.0000, 15.0000,  5.0000,
         5.0000,  5.0000, 10.0000, 15.00

In [131]:
torch.from_numpy(np.array(list(x.values()))).to('cpu:0')

tensor([500, 500, 500])

In [134]:
indices

tensor([15, 10, 15, 10, 15, 10, 15, 10, 10, 15, 10,  5, 10, 10, 10, 15,  5, 10,
         5,  5, 10, 10,  5, 10,  5,  5, 10, 15,  5, 15, 15, 15, 10, 10,  5, 15,
         5,  5,  5, 10, 10, 15,  5, 15, 10, 15,  5, 10,  5, 15, 15, 15, 10, 15,
        15, 10, 15,  5,  5, 10,  5, 10, 10, 15,  5,  5, 10, 15, 10, 15, 10, 10,
        10,  5, 10,  5, 15,  5,  5,  5,  5,  5, 15, 10, 15, 15, 10,  5,  5,  5,
         5, 15,  5,  5, 15,  5,  5,  5, 10, 15, 15, 15, 10,  5,  5, 15, 10, 10,
         5, 15, 10, 15,  5, 15, 10, 10, 15, 10,  5,  5, 15, 10,  5, 15, 15,  5,
        15, 15])

In [137]:
m = {5: 1.9, 10: 2.2}
result=[m.get(i.item(), 1) for i in indices]
print(result)

[1, 2.2, 1, 2.2, 1, 2.2, 1, 2.2, 2.2, 1, 2.2, 1.9, 2.2, 2.2, 2.2, 1, 1.9, 2.2, 1.9, 1.9, 2.2, 2.2, 1.9, 2.2, 1.9, 1.9, 2.2, 1, 1.9, 1, 1, 1, 2.2, 2.2, 1.9, 1, 1.9, 1.9, 1.9, 2.2, 2.2, 1, 1.9, 1, 2.2, 1, 1.9, 2.2, 1.9, 1, 1, 1, 2.2, 1, 1, 2.2, 1, 1.9, 1.9, 2.2, 1.9, 2.2, 2.2, 1, 1.9, 1.9, 2.2, 1, 2.2, 1, 2.2, 2.2, 2.2, 1.9, 2.2, 1.9, 1, 1.9, 1.9, 1.9, 1.9, 1.9, 1, 2.2, 1, 1, 2.2, 1.9, 1.9, 1.9, 1.9, 1, 1.9, 1.9, 1, 1.9, 1.9, 1.9, 2.2, 1, 1, 1, 2.2, 1.9, 1.9, 1, 2.2, 2.2, 1.9, 1, 2.2, 1, 1.9, 1, 2.2, 2.2, 1, 2.2, 1.9, 1.9, 1, 2.2, 1.9, 1, 1, 1.9, 1, 1]
